name: release
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Create release
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@ca6063f4ed81b55db15b8c42d1b6f7925866342d # v3
        id: release
        with:
          command: manifest

  publish:
    name: Publish to npm (fake)
    runs-on: ubuntu-latest
    needs: release
    if: ${{ needs.release.outputs.releases_created }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile
      - run: pnpm lint
